using System;


class MaxSubmatrixSum
{

    private static void PrintMatrix(int[,] matrix, int maxRow, int maxCol)
    {

        string divider = "+";
        for (int cols = 0; cols < matrix.GetLength(1); cols++)
            divider = divider + "---+";
        Console.WriteLine(divider);
        for (int rows = 0; rows < matrix.GetLength(0); rows++)
        {
            for (int cols = 0; cols < matrix.GetLength(1); cols++)
            {
                Console.Write("|");
                if (rows >= maxRow && rows <= maxRow + 2 && cols >= maxCol && cols <= maxCol + 2)
                    Console.ForegroundColor = ConsoleColor.Yellow;
                Console.Write("{0,3}", matrix[rows, cols]);
                Console.ForegroundColor = ConsoleColor.Gray;
            }
            Console.WriteLine("|");
            Console.WriteLine(divider);
        }
        Console.WriteLine();
    }

    static int CalcSum(int startRow, int startCol, int[,] matrix)
    {
        int sum = 0;
        for (int row = startRow; row < startRow + 3; row++)
            for (int col = startCol; col < startCol + 3; col++)
                sum = sum + matrix[row, col];
        return sum;
    }

    static void Main()

    /* Write a program that reads a rectangular matrix of size N x M and 
     * finds in it the square 3 x 3 that has maximal sum of its elements. */
    {
        int n;
        int m;

        int[,] matrix = 
        {   {  0,  5, 12,  4,  9},
            { -5,  9,  6,  4,  1},
            { 11,  5, -8,  6,  9},
            {  9,  2,  3,  4,  9}     };

        Console.Write("Enter 'A' for autogenerated random array or 'P' for hardcoded array: ");
        string s = Console.ReadLine().ToUpper();
        Console.WriteLine();
        if (s == "A")
        {
            Random rnd = new Random();
            n = rnd.Next(6, 10);
            m = rnd.Next(10, 15);
            matrix = new int[n, m];
            for (int row = 0; row < n; row++)
                for (int col = 0; col < m; col++)
                    matrix[row, col] = rnd.Next(20) - 10;
        }
        else
        {
            n = matrix.GetLength(0);
            m = matrix.GetLength(1);
        }

        int maxSum = int.MinValue;
        int tmpSum = 0;
        int maxRow = 0;
        int maxCol = 0;
        for (int row = 0; row < n - 2; row++)
            for (int col = 0; col < m - 2; col++)
            {
                tmpSum = CalcSum(row, col, matrix);
                if (tmpSum > maxSum)
                {
                    maxRow = row;
                    maxCol = col;
                    maxSum = tmpSum;
                }
            }

        PrintMatrix(matrix, maxRow, maxCol);
        Console.WriteLine("Maximal sum is {0}", maxSum);
    }
}
