//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoChat.Data {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class MongoChatSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MongoChatSettings defaultInstance = ((MongoChatSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MongoChatSettings())));
        
        public static MongoChatSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mongodb://user:alabala123@ds063879.mongolab.com:63879/mongochat")]
        public string MongoConnectionString {
            get {
                return ((string)(this["MongoConnectionString"]));
            }
            set {
                this["MongoConnectionString"] = value;
            }
        }
    }
}
