//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.Employees1 = new HashSet<Employees>();
            this.EmployeesProjects = new HashSet<EmployeesProjects>();
            this.Reports = new HashSet<Reports>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public decimal Salary { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public int DepartmentID { get; set; }
    
        public virtual Departmens Departmens { get; set; }
        public virtual ICollection<Employees> Employees1 { get; set; }
        public virtual Employees Employees2 { get; set; }
        public virtual ICollection<EmployeesProjects> EmployeesProjects { get; set; }
        public virtual ICollection<Reports> Reports { get; set; }
    }
}
