//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int id { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime TimeOfReport { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
