//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLToMongoTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        public int CompetitionID { get; set; }
        public string Sport { get; set; }
        public string Discipline { get; set; }
        public string Event { get; set; }
    }
}
