//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummerOlympiads.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Athlete
    {
        public Athlete()
        {
            this.Rankings = new HashSet<Ranking>();
        }
    
        public int AthleteId { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> NationalityId { get; set; }
    
        public virtual Nationality Nationality { get; set; }
        public virtual ICollection<Ranking> Rankings { get; set; }
    }
}
