//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummerOlympiads.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Rankings = new HashSet<Ranking>();
        }
    
        public int EventId { get; set; }
        public string Name { get; set; }
        public int DisciplineId { get; set; }
        public int SummerOlympiadId { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual SummerOlympiad SummerOlympiad { get; set; }
        public virtual ICollection<Ranking> Rankings { get; set; }
    }
}
