//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummerOlympiads.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OlympiadsEntities : DbContext
    {
        public OlympiadsEntities()
            : base("name=OlympiadsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Athlete> Athletes { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Discipline> Disciplines { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<Ranking> Rankings { get; set; }
        public virtual DbSet<Sport> Sports { get; set; }
        public virtual DbSet<SummerOlympiad> SummerOlympiads { get; set; }
    }
}
