//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummerOlympiads.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ranking
    {
        public int RankId { get; set; }
        public int AthleteId { get; set; }
        public int EventId { get; set; }
        public int Rank { get; set; }
    
        public virtual Athlete Athlete { get; set; }
        public virtual Event Event { get; set; }
    }
}
