using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace _07.PathBetweenTwoCells
{
    class Maze
    {
        public static string[] maze = new string[]
        {

"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"  x     x   x     x   x x     x     x       x   x       x   x         x   x  ",
"x x xxx xxx x xxx xxx x x xxx x x xxx xxxxx x x x xxxxx xxx x xxxxxxx xxx x x",
"x x x   x   x   x   x   x   x   x   x     x x x x     x     x   x   x     x x",
"x x x xxx xxxxx xxx xxx xxxxxxxxx x xxxxx x x xxxxxxx xxxxxxxxx x x x xxxxx x",
"x   x   x x     x   x x         x x x     x x x     x x         x x   x   x x",
"xxxxxxx x x xxxxx xxx xxxxxxx xxx x x xxxxx x x xxx x xxxxxxxxxxx xxxxx x x x",
"x   x     x x x   x   x     x   x x   x   x x     x             x   x   x x  ",
"x xxx xxxxx x x xxx xxx x x xxx x xxxxx x x x xxxxxxxxxxxxxxxxx xxx x xxx xxx",
"x     x     x   x x     x x x   x       x x     x   x             x     x x  ",
"x xxxxxxx xxxxxxx xxxxxxxxx x xxxxxxxxxxxxxxx x x xxx xxxxx xxxxxxxxx x xxx x",
"x     x   x         x     x x     x   x       x x     x   x   x   x   x x    ",
"xxx x x xxx xxxxxxx x xxx x xxx x x x x xxxxxxx xxxxxxx x xxx x x xxxxx x x x",
"x   x x   x       x x x   x x   x x x x   x     x   x   x     x x   x   x x x",
"x xxxxxxx xxxxxxxxx x x xxx xxxxx x x xxx xxxxxxx x x xxxxxxxxxxxxx x xxx x x",
"x x     x x   x   x   x   x x   x x x   x   x     x x   x   x   x x x x   x  ",
"x xxxxx x x x x x x xxxxx x x x x x x x xxx x xxxxx xxx x x x x x x x x xxxxx",
"x   x   x   x x x x   x   x   x x   x x x   x   x x   x   x   x x x x   x   x",
"xxx x xxxxxxx x x x x x xxx xxx x xxx xxx xxxxx x x xxxxxxxxxxx x x xxxxxxx x",
"x   x x   x   x x   x x x   x   x   x x   x       x     x       x   x       x",
"x xxx x x x xxx xxxxx x x xxx xxxxx xxx x xxxxxxx xxxxx x xxxxxxxxx x xxxxxxx",
"x       x x   x x     x x x   x   x   x x   x     x       x       x x   x    ",
"xxxxx xxx xxx x x xxxxx x x xxx x xxx x xxx x x xxx xxx xxxxxxx x x x x x xxx",
"x     x x   x x x     x   x x   x   x x   x   x x   x   x   x   x   x x      ",
"x x xxx xxxxx x xxxxx xxxxx x xxxxx x xxx xxxxx xxxxxxxxx x x x xxxxxxxxx xxx",
"x x     x   x x x   x   x     x   x       x   x           x   x   x     x x  ",
"x xxxxx x x x x x x xxx x xxxxx x xxx xxxxx x xxx xxxxxx xxxxxxxx x xxx x x x",
"x     x   x   x x x     x     x x   x     x x       x         x   x   x   x  ",
"xxxxx xxx x xxx x xxxxxxxxxxx x xxx xxx x x xxxxxxx x xxxxxxx x xxx xxxxxxx x",
"x x   x   x     x x   x     x x   x   x x x   x     x x     x     x   x   x x",
"x x xxx xxxxxxxxx xxx x xxxxx xxx xxx x xxxxx x x xxx xxxxx xxxxx x x xxx x x",
"x x x       x   x     x       x     x x       x x x x   x   x   x x x     x  ",
"x x xxxxxxx x x xxxxxxxxxxxxxxx xxx xxxxxxxxxxx x x xxx x xxx x x xxxxxxx x x",
"x x   x   x x x   x             x   x       x   x x   x   x   x x     x x x x",
"x xxx xxx x x xxx x xxxxxxxxxxxxx xxx x xxxxx xxx x x xxxxxxxxx xxxxx x x x x",
"x     x   x   x   x x           x     x x x   x x x x x     x x   x   x   x x",
"x x xxx xxxxxxx xxxxx xxxxxxxxx x xxxxx x x xxx x x x x xxx x x x x xxxxx x x",
"x x   x   x   x x x   x       x   x   x     x     x x   x     x x x x   x x  ",
"x xxx xxx xxx x x x xxxxxxx x xxxxx x xxxxxxx x xxx xxxxx xx xxxx x x x x xxx",
"x   x   x   x   x x x x   x x x     x   x     x x       x         x   x     x",
"xxx xxxxxxx xxxxx x x x x x x x xxxxxxx x xxxxx x xxxxx xxx xxxxxxxxxxxxxxx x",
"x x   x   x   x       x x x x   x x   x x   x x x x     x                   x",
"x xxx x x xxx x x xxxxx x x xxxxx x x xxxxx x x x x xxxxxx xxxxxxxx x xxx x x",
"x   x   x   x   x   x   x x x   x   x       x   x x   x     x x   x   x   x x",
"xxx xxx x xxxxxxxxxxx x x x xxxxxxxxx xxxxxxx x xxxxx xxxxx x xxxxx x x x xxx"


/*            "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"  x     x   x     x   x x     x     x       x   x       x   x         x   x       x       x         x",
"x x xxx xxx x xxx xxx x x xxx x x xxx xxxxx x x x xxxxx xxx x xxxxxxx xxx x xxxxx x xxx x xxxxx xxx x",
"x x x   x   x   x   x   x   x   x   x     x x x x     x     x   x   x     x x   x x x x x x   x x   x",
"x x x xxx xxxxx xxx xxx xxxxxxxxx x xxxxx x x xxxxxxx xxxxxxxxx x x x xxxxx x x x x x x x x x x xxxxx",
"x   x   x x     x   x x         x x x     x x x     x x         x x   x   x x x   x   x x x x x     x",
"xxxxxxx x x xxxxx xxx xxxxxxx xxx x x xxxxx x x xxx x xxxxxxxxxxx xxxxx x x xxxxxxxxxxx x xxx xxx x x",
"x   x     x x x   x   x     x   x x   x   x x     x             x   x   x x   x   x   x x     x   x x",
"x xxx xxxxx x x xxx xxx x x xxx x xxxxx x x x xxxxxxxxxxxxxxxxx xxx x xxx xxx x x x x x x xxxxx xxxxx",
"x     x     x   x x     x x x   x       x x     x   x             x     x x   x x   x x x       x   x",
"x xxxxxxx xxxxxxx xxxxxxxxx x xxxxxxxxxxxxxxx x x xxx xxxxx xxxxxxxxx x xxx xxxxxxxxx x xxxxxxxxx x x",
"x     x   x         x     x x     x   x       x x     x   x   x   x   x x     x       x x x   x   x x",
"xxx x x xxx xxxxxxx x xxx x xxx x x x x xxxxxxx xxxxxxx x xxx x x xxxxx x x x x xxxxx x x x x x x xxx",
"x   x x   x       x x x   x x   x x x x   x     x   x   x     x x   x   x x x   x   x x   x x   x   x",
"x xxxxxxx xxxxxxxxx x x xxx xxxxx x x xxx xxxxxxx x x xxxxxxxxxxxxx x xxx x xxxxx x x xxx x xxxxxxx x",
"x x     x x   x   x   x   x x   x x x   x   x     x x   x   x   x x x x   x   x x x x   x x   x   x x",
"x xxxxx x x x x x x xxxxx x x x x x x x xxx x xxxxx xxx x x x x x x x x xxxxx x x x xxx x xxxxx x x x",
"x   x   x   x x x x   x   x   x x   x x x   x   x x   x   x   x x x x   x   x x   x   x x     x x   x",
"xxx x xxxxxxx x x x x x xxx xxx x xxx xxx xxxxx x x xxxxxxxxxxx x x xxxxxxx x xxxxxxx x xxxxx x x xxx",
"x   x x   x   x x   x x x   x   x   x x   x       x     x       x   x       x   x     x x   x x x   x",
"x xxx x x x xxx xxxxx x x xxx xxxxx xxx x xxxxxxx xxxxx x xxxxxxxxx x xxxxxxxxx x xxxxx x x x x xxx x",
"x       x x   x x     x x x   x   x   x x   x     x       x       x x   x       x     x   x x x x   x",
"xxxxx xxx xxx x x xxxxx x x xxx x xxx x xxx x x xxx xxx xxxxxxx x x x x x xxxxxxxxxxx xxxxx x xxx x x",
"x     x x   x x x     x   x x   x   x x   x   x x   x   x   x   x   x x       x     x x     x   x x x",
"x x xxx xxxxx x xxxxx xxxxx x xxxxx x xxx xxxxx xxxxxxxxx x x x xxxxxxxxx xxx x xxx x x xxxxxxx x x x",
"x x     x   x x x   x   x     x   x       x   x           x   x   x     x x   x   x x x           x x",
"x xxxxx x x x x x x xxx x xxxxx x xxx xxxxx x xxx xxxxxx xxxxxxxx x xxx x x xxxxxxx x xxxxxxxxxxxxx x",
"x     x   x   x x x     x     x x   x     x x       x         x   x   x   x         x x x       x   x",
"xxxxx xxx x xxx x xxxxxxxxxxx x xxx xxx x x xxxxxxx x xxxxxxx x xxx xxxxxxx xxxxx xxx x x xxxxx xxxxx",
"x x   x   x     x x   x     x x   x   x x x   x     x x     x     x   x   x x   x x   x   x         x",
"x x xxx xxxxxxxxx xxx x xxxxx xxx xxx x xxxxx x x xxx xxxxx xxxxx x x xxx x x x x x xxxxxxxxxxx x x x",
"x x x       x   x     x       x     x x       x x x x   x   x   x x x     x   x x x x           x x x",
"x x xxxxxxx x x xxxxxxxxxxxxxxx xxx xxxxxxxxxxx x x xxx x xxx x x xxxxxxx x xxx xxx x xxxxxxxxxxx xxx",
"x x   x   x x x   x             x   x       x   x x   x   x   x x     x x x x x     x   x       x   x",
"x xxx xxx x x xxx x xxxxxxxxxxxxx xxx x xxxxx xxx x x xxxxxxxxx xxxxx x x x x xxxxxxxxx x xxxxxxxxx x",
"x     x   x   x   x x           x     x x x   x x x x x     x x   x   x   x x x     x x x           x",
"x x xxx xxxxxxx xxxxx xxxxxxxxx x xxxxx x x xxx x x x x xxx x x x x xxxxx x x x xxx x x xxxxxxxxxxxxx",
"x x   x   x   x x x   x       x   x   x     x     x x   x     x x x x   x x   x x         x         x",
"x xxx xxx xxx x x x xxxxxxx x xxxxx x xxxxxxx x xxx xxxxx xx xxxx x x x x xxx x xxxxxxxxx x x xxxxx x",
"x   x   x   x   x x x x   x x x     x   x     x x       x         x   x     x x       x   x x   x   x",
"xxx xxxxxxx xxxxx x x x x x x x xxxxxxx x xxxxx x xxxxx xxx xxxxxxxxxxxxxxx xxxxxxxxx x xxx xxx xxxxx",
"x x   x   x   x       x x x x   x x   x x   x x x x     x                   x   x   x x       x     x",
"x xxx x x xxx x x xxxxx x x xxxxx x x xxxxx x x x x xxxxxx xxxxxxxx x xxx x x x x x x xxx xxx xxxxx x",
"x   x   x   x   x   x   x x x   x   x       x   x x   x     x x   x   x   x x x x x x   x x   x x   x",
"x x x x x x xxxxxxx x xxx x xxx x xxxx xxxxxx xxx xxx x xxx x x x xxxxx xxxxx x xxx xxx x xxxxx x xxx",
"x x x x x x x x   x   x   x       x     x   x     x x   x x x   x     x x   x x   x   x x x     x x x",
"x xxx x xxx x x x xxxxx xxxxxxx xxx xxx x x x xxxxx xxxxx x xxxxxxxxx x x x x xxx x x xxx x xxx x x x",
"x     x   x x   x   x   x     x x x x   x x       x     x   x   x     x   x x x   x x x   x   x   x x",
"x xxxxxxx x xxxxxxx x xxx xxx x x x x xxx x x xxx xxxxx x x x x x xxxxxxxxx x x xxxxx x xxxxx xxxxx x",
"x x     x x         x x x x x   x   x     x x x       x   x x x   x x     x   x     x x       x   x x",
"xxx xxx x xxxxxxxxxxx x x x xxxxxxxxx xxxxxxx x xxxxx xxxxx x xxxxx x x x xxxxxxxxx x x xxx xxxxx x x",
"x   x x x     x   x   x     x         x       x x     x   x x x       x x               x x x   x   x",
"x xxx x xxx x x x xxxxxxx xxx xxxxxxxxxxxxxxxxx x xxxxx x x x xxx xxxxx xxx xxx xxxxx xxx x x x xxx x",
"x     x     x   x       x x   x     x     x     x     x x   x x       x x x   x x   x x x   x x x   x",
"xxxxxxxxxxxxxxxxxxxxxxx x x xxx xxx xxx xxx xxxxxxxxx x xxxxx x xxxxxxx x xxx xxx x x x xxxxx x x xxx",
"x     x   x             x x x   x     x     x x   x   x     x   x     x x     x   x x x   x   x   x x",
"x xxx x xxx xxxxxxxxxxxxx x x xxxxxxx xxxxxxx x x x x xxxxx xxxxxxxxx x x xxxxx xxxxx xxx x xxxxxxx x",
"x x   x x   x   x     x   x   x     x x   x     x x x     x   x       x x             x x x x x     x",
"x xxxxx x xxxxx x xxxxx xxxxxxx xxx x xxx x x x x x xxxxx xxx x xxx xxxxxxxxx xxx xxxxx x x x x xxx x",
"x   x     x     x     x x       x   x   x x x x x x x   x x x           x   x     x       x   x   x x",
"xxx xxxxx x x xxx xxx x x xxxxxxx x xxx x x x xxx x x x x x xxxxx xxxxx x x xxxxxxx xxx xxx xxxxx x x",
"x x     x x x     x x   x x x     x         x x   x   x x x x   x x   x   x x x   x   x   x     x x x",
"x xxxxx xxx xxxxx x xxx x x x xxxxxxxxxxxxxxxxx xxxxxxx x x x xxx x xxx xxx x x x xxx xxx xxx x x xxx",
"x     x     x   x   x   x x x     x       x     x     x x   x   x x     x   x   x   x   x   x x x   x",
"xxxxx xxxxxxx x xxxxxxxxx x xxx xxx xxxxx x xxxxx xxx xxx xxxxx x xxx x x x xxx xxx xxxxxxx x x xxx x",
"x     x     x x   x   x x   x   x   x   x   x x   x                 x x   x   x   x     x   x x   x x",
"x xxx x xxx x xxx xxx x xxxxx xxx xxxxx xxxxx x xxxx xxxxxx xxx xxx x xxxxx xxxxx xxxxx x xxxxxxx x x",
"x x x   x   x   x   x         x   x   x x     x x     x   x   x   x x   x   x   x   x   x     x     x",
"x x xxxxx xxxxx xxx xxx x xxxxx xxxxx x x xxxxx x xxx x x x x x x x xxx x x x x xxx x xxxxxxx xxxxx x",
"x x     x x   x   x   x x x     x   x x x     x x   x   x   x x   x x   x x   x x   x       x   x   x",
"x x x x x xxx xxx xxx x x x xxxxxxx x x xxxxx x xxx xxx xxxxx x xxx x xxx xxxxx xxx xxxxxxx xxx xxx x",
"x x x x       x   x x x x x       x   x   x x   x x x x x     x   x x     x x   x   x     x   x x   x",
"x x xxxxxxx xxx xxx x x x xxx x x x xxxxx x xxx x x x x x xx xxxx x xxxxx x x xxx x x xxx xxxxx x x x",
"x x     x     x   x x x x   x x x         x     x   x     x       x x   x x x x   x x x   x     x x x",
"x xxxxx x xxx xxx x x x xxx x xxxxxxx xxxxxxxxx xxxxxxx xxx xxxxxxx x x xxx x xxxxx x x xxx x xxx x x",
"x x     x   x x   x   x x   x x     x   x     x     x x   x         x       x x     x x x     x   x x",
"x x xxxxxxx x x xxx xxx x xxxxx xxxxxxx x xxx xxxxx x x x xxx xxxxxxx xxxxx x x xx xx x x xxxxx xxxxx",
"x x   x   x x   x   x   x x           x x   x x     x         x     x     x   x x     x   x   x     x",
"x xxx xxx x xxxxxxx x x x x xxxxxxxxx x xxxxx xxx xxx xxxxxxxxx xxxxxxxxx x xxx x xxxxxxxxxxx xxxxx x",
"x x x     x       x   x x   x     x   x x   x   x   x   x   x       x   x x x   x x x       x       x",
"x x xxxxxxxxxxxxx xxxxxxxxxxx xxx x x x x x xxx xxx xxx x x x xxxxx x xxx x x xxx x x xxxxx x xxxxxxx",
"x x     x   x             x     x   x x   x   x     x   x   x x   x       x x   x x   x   x x   x   x",
"x x xxx x x xxxxx xxxxxxx xxx x xxxxxxxxxxxxx xxx xxx x x x xxx xxxxx xxx x xxx x xxxxx x x x xxx xxx",
"x x x x x x     x   x   x     x   x     x   x x   x x x   x   x x       x x   x     x   x   x   x   x",
"x x x x x xxxxx xxx xxx xxxxxxxxx x xxx x x x x xxx x xxxxx x x x xxxxx x xxx x xxxxx xxxxx xxx xxx x",
"x   x x   x   x     x     x       x   x x x x x   x x x   x x x   x   x x   x x     x   x   x   x   x",
"xxxxx xxxxx x xxxxxxx x xxx x xxxxxxx x x x x xxx x x xxx x x x xxxxx x xxxxx xxxxx xxxxx xxx xxxxx x",
"x   x   x   x         x x   x       x x   x x     x   x   x x x   x   x x   x x   x     x     x     x",
"x xxx x x xxxxxxxxxxxxxxx xxxxxxx x x xxxxx xxx xxxxxxx x x x xxx x xxxxx x x xxx xxxxx xxx xxx x xxx",
"x     x         x             x   x x   x x x       x   x   x   x x x     x x           x     x x   x",
"xxxxxxx xxxxxxxxx xxxxxxxxxxxxx xxx xxx x x xxxxx x x xxxxxxxxx x x x xxxxx xxxxx x xxxxxxx xxx xxx x",
"x     x               x         x       x   x     x x   x   x   x   x x x   x   x x       x x   x   x",
"x xxxxxxxxxxxxxxxxxxx x xxxxxxx x x xxxxx xxx x xxxxxxx x x x xxxxxxx x x xxx x x xxxxx x x x xxx xxx",
"x     x         x   x x   x   x x x     x     x   x     x x x x x   x   x   x x x x   x x x x x x x x",
"xxxxx xxx xxx x x x x xxx x x xxx xxxxx xxxxxxxxx x xxxxx x x x x x xxxxx x x x x x x x x x x x x x x",
"x         x   x   x   x   x x     x   x     x     x x x   x x x x x       x x x x   x x x x x   x   x",
"x xxxxxxxxx xxxxxxxxxxx xxxxxxxxxxx x xxx xxx xxx x x x xxx x x x xxxxxxxxx xxx xxxxx x x x x xxxxx x",
"x     x     x   x x     x         x x   x x   x     x   x x x   x x   x             x   x x   x   x x",
"xxxxx x xxxxx x x x xxxxxxxxxxx x x xxxxx x xxx xxx xxxxx x xxxxx x xxx xxx xxx xxxxx x x x x xxx x x",
"x     x       x   x             x x       x   x   x       x       x     x   x         x           x  ",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"  */
        };

    }
}

